# Step 1: Use official Node.js image
FROM node:20-alpine

ARG V_PORT=5000

ENV DATABASE_URL=mongodb+srv://uk:admin123@cluster0.08kb988.mongodb.net
ENV PORT=${V_PORT}
ENV DATABASE_NAME=landing_page

# Step 2: Set working directory
WORKDIR /app

# Step 3: Copy package files
COPY . /app/

# Step 4: Install dependencies
RUN npm install

# Step 6: Build TypeScript
RUN npm run build

# Step 7: Expose app port
EXPOSE ${V_PORT}

# Start the server
CMD ["node", "dist/index.js"]